ALTER USER 'root'@'localhost' IDENTIFIED BY 'Welc0me_2017';
CREATE USER 'root'@'%' IDENTIFIED BY 'Welc0me_2017';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'Welc0me_2017';
FLUSH PRIVILEGES;
